### PR TITLE
Fink sandbox

### PR DESCRIPTION
**Pull request by jwhowarth**
Add support to sandbox fink using the directories listed in %p/etc/fink.sb. This allows users who need to build fink packages against /usr/local to simply delete that line. Also, anyone wanting to test support for fink x.org packages to replace Xquartz can just append '/opt/X11' to fink.sb.

### CODE REVIEW

**Comment by jwhowarth** [comment]
Verified by building the gcc5 package, against a build of gmp-6.1.0 installed in /usr/local, that the fink-sandbox changes work properly. 
Note that the gcc5 and gcc6 packages now require --with-local-prefix=%p on ConfigureParams (ala MacPorts) in order to avoid a configure failure from the xgcc compiler attempting to access /usr/local/include.

**Comment by akhansen** [comment]
If there aren't any objections, I'll bring this in as a feature development branch.

**Comment by jwhowarth** [comment]
Just to clarify, this pull has changed in design since it was started. The current design to be merged is...

1) Enabling the sandbox usage by default (except during fink bootstraps)
2) Adding a 'NoSandbox' field for the Info files which can be used to
disable the sandbox on a per package basis.
3) Retaining the --build-in-sandbox/--no-build-in-sandbox fink flags
which override the other settings.

The --no-build-in-sandbox fink flag can be used to disable the sandbox
in any fink build while the --build-in-sandbox fink flag can be used
to override 'NoSandbox: true' in a particular info file.

**Comment by akhansen** [comment]
Now present in the 'sandbox-build' branch of fink/fink

**Pull request merged**
