### PR TITLE
Selfupdate-git and -svn, take three

### PR DESCRIPTION
**Pull request by fingolfin**
This replaces PR #78 -- the content is identical, but I have replaced the old "selfupdate-git" branch in fink/fink with my rebased and cleaned code, and based this PR on that. Thus now anybody with write access to the fink repository can directly modify it. (I would still prefer to work on this differently, with people forking my version of the branch, then submitting changes back via PRs and/or patch mails, but since this is not popular, let's do it this way for the sake of progress!)

I have not (yet?) made any attempt yet to transfer the discussion from there (it wasn't much to start with).

[Review on Reviewable](https://reviewable.io/reviews/fink/fink/97)

### CODE REVIEW

**Comment by dak180** [comment]
This depends on fink/scripts#33.

**Comment by dak180** [comment]
@fink/fink-developers  when the git dists gets set up where should all the stuff in experimental go, in a branch or a sub directory?

**Comment by akhansen** [comment]
We never actually decided that.  

What I'd advocate would be not to migrate experimental automatically and let individual maintainers decide if they want to continue to use CVS, use their own clone, or employ some other method.

I'd rather not have people's experimental packages be part of the official repository, because that implies that we support them.

**Comment by dak180** [comment]
@akhansen in that case what I can do is set each person's experimental directory as its own branch in my personal fork of the dists so if they decide to convert to git all they will have to do is pull the appropriate branch into their own clone; how does that sound to you?

**Comment by akhansen** [comment]
That sounds OK.

**Comment by akhansen** [comment]
I guess the "added some commits" entry doesn't bother to change the date. ;-)  I just synced with master again today.  

Other than an officially blessed dists/ tree, where are we at?  Are we still lacking relevant scripts?

Operationally, we'll want a CVS freeze before we switch over, to avoid having updates get lost.

**Comment by dak180** [comment]
@akhansen There is only one script that needs to be finished @TheSin- started working on it but I do not know if it is finished yet: https://github.com/fink/scripts/blob/master/distfiles/finkdist.

**Comment by TheSin-** [comment]
that script is complete enough to match what we currently have and it's currently running on snitch now.  So I believe all scripts are done and thus we can plan to start the migration, I'll obviously need to switch a bunch of stuff on snitch but I can do that as we go.

**Comment by dak180** [comment]
I think the only two things left are freezing cvs so I can run the [conversion](https://github.com/dak180/fink-distsConversion) (a recent dry run can be found [here](https://github.com/dak180/fink-dists)) and updating the [git script](https://github.com/fink/scripts/tree/master/selfupdate-mirror#fink-info-git-as-an-example-for-future-use-only) to point to the correct repo.

**Comment by fingolfin** [comment]
I just noticed there was activity on this PR I opened ages ago. So I just rebased it (instead of all those merges) onto the master branch.

**Comment by akhansen** [comment]
Refreshing this.  Since the CVS repository is becoming nonfunctional, I'd like some eyes here so that we can get moved over to something that works.

Either that or we can pull up stakes and move on.  Your call.

**Comment by clepple** [comment]
🎉

**Pull request merged**
