### PR TITLE
Tidy up the X11 detection a bit.

### PR DESCRIPTION
**Pull request by akhansen**
Include /opt/X11 as a valid place to search for 10.8 and later.

### CODE REVIEW

**Comment by akhansen** [comment]
There are two elements to this:

1.  There are quite a number of hardcoded literal lists of the form ('/usr/X11', '/usr/X11R6') and other instances where we just use "/usr/X11R6".  I figured that it might be nice to standardize them.
2.  Since 3 out of 4 of our supported platforms use /opt/X11 as their _real_ X11 path, why not search there first for files rather than relying on the /usr/X11 and /usr/X11R6 convenience symlinks?    The downside is that individual packages _do_ rely on them.

**Comment by nieder** [comment]
I think that the `@x11_dirs` idea is a good one as is searching in /opt. But I don't see the downside to this particular patch (besides the general downside that pkgs shouldn't be assuming /usr/X11R6).

Also, is there any performance benefit to changing line 77 in VirtPackage.pm to put Xquartz first and decrease the number of files searched.

Since we're normalizing X11 directory patch searches, is it worth generating a %x11_root expansion that's platform dependent, going through dists and replacing all /usr/X11{,R6} with %x11, and then enforcing its use for new files? That will require a new InfoN, won't it?

**Comment by akhansen** [comment]
Yeah, it's probably a good idea to do the re-ordering on line 77.

The one minor downside is that for 10.7 we need /usr/X11, and so we either have to assume the /usr/X11 symlink on 10.8 and later, or have different 10.7 packaging, or add a new field like you suggested.

**Comment by akhansen** [comment]
It doesn't appear that there were any objections.

**Pull request merged**
