### PR TITLE
support 10.15.2-10.15.4

### PR DESCRIPTION
**Pull request by nieder**

### CODE REVIEW

**Comment by TheSin-** [comment]
I'll test it but it seems fine and inline with what we typically do.

**Comment by TheSin-** [comment]
I'm not sure if it belongs here but it seems that with 10.15.2 came Xcode cli tools 11.3 and it seems the have broken the f-v-p for it.  I can't remember if it always was but it now says clitools is 0-0

```
WARNING: Xcode.app version (11.3) and Xcode Command Line Tools version (0.0) may not be compatible.
You may experience build errors.
```

**Comment by nieder** [comment]
Try `sudo xcodebuild -license` ? Sometimes updating CLI or Xcode itself resets the license, and f-v-p uses some bits to determine the Xcode/CLI version.

**Comment by TheSin-** [comment]
was worth a shot but didn't help sadly.

**Comment by nieder** [comment]
CLI are currently checked by `pkgutil --pkg-info com.apple.pkg.CLTools_Executables` (see https://github.com/fink/fink/blob/master/perlmod/Fink/VirtPackage.pm#L897 ) If that receipt is gone, or the version format changed, then we can hate Apple (again).

**Comment by TheSin-** [comment]
that is the issue then ;)

```
pkgutil --pkg-info com.apple.pkg.CLTools_Executables
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
```

**Comment by nieder** [comment]
`pkgutil --file-info /Library/Developer/CommandLineTools/usr/bin/flex` should tell you the new name of the package that the CLT live in. This is with Xcode10.1:
```
$ pkgutil --file-info /Library/Developer/CommandLineTools/usr/bin/flex
volume: /
path: /Library/Developer/CommandLineTools/usr/bin/flex

pkgid: com.apple.pkg.CLTools_Executables
pkg-version: 10.1.0.0.1.1539992718
install-time: 1557926225
uid: 0
gid: 80
mode: 755
```

**Comment by TheSin-** [comment]
sadly no :(

```
pkgutil --file-info /Library/Developer/CommandLineTools/usr/bin/flex
volume: /
path: /Library/Developer/CommandLineTools/usr/bin/flex
```

**Comment by nieder** [comment]
On my 10.15.1/xcode11.3 VM, f-v-p finds the CLT.

Since `pkgutil --pkg-info com.apple.pkg.CLTools_Executables` doesn't return a known package for you, maybe try `pkgutils --forget com.apple.pkg.CLTools_Executables` to really make it forget, and then retry `xcode-select --install` ?

**Comment by TheSin-** [comment]
```
pkgutil --forget com.apple.pkg.CLTools_Executables
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
[~]$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

Maybe if fink gets 0-0 it should halt and give a download link tell users to reinstall due to a macOS bug?

**Comment by nieder** [comment]
I just went from 10.15.1 to 10.15.3. Fink lost track of the CLT install and `xcode-select --install` told me they were already installed. The only way to get Fink to recognize them again was to download the installer from developer.apple.com and manually reinstall. This is tangential to recognizing system versions, though.

**Comment by TheSin-** [comment]
The way I keep doing it is

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

it's a PITA though I hope apple fixes it.  It has happened on every update so far.

**Comment by nieder** [comment]
Ping on reviewing the recognized versions change

**Comment by nieder** [comment]
No change to system-perl.

**Comment by nieder** [comment]
Committing. It's a minor change that follows the existing pattern for all previous releases.

**Pull request merged**
