### PR TITLE
Changes to Engine.pm to allow upgrades to 10.14.5 distribution

### PR DESCRIPTION
**Pull request by PovlAbrahamsen**
I think this should create the correct checks to allow upgrades to 10.14.5. Tested on my machine running 10.14.5 - and appears to work...

### CODE REVIEW

**Comment by nieder** [comment]
@mrvacbob You have 10.14.6beta, right? Does this work for you to install and/or update on 10.14.6beta? The change here sits atop of the changes in #190.

**Comment by mrvacbob** [comment]
It bootstraps, seems to work.
```
  i   system-perl                         5.18.4-1                   [virtual package representing perl]
 p   system-perl5184                                                [virtual package]
```

**Comment by nieder** [comment]
WFM as well on 10.14.6beta.

**Comment by nieder** [comment]
Merging to my 10.14.5 branch to simplify testing.

**Pull request merged**
