### PR TITLE
Add --prefix option, displays the prefix / basepath / %p

### LINKED ISSUE #149: Add `fink prefix` or `fink --prefix` to get the prefix
It would be nice if one could use `fink prefix` or `fink --prefix` and it would print `/sw` (or whatever your Fink prefix is) to stdout, similar to `brew --prefix`. This is handy for writing scripts that try to use Fink installed libraries, if installed, w.o. having to hardcode `/sw`.

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #149

### CODE REVIEW

**Comment by dmacks** [comment]
Looks fine to me!

**Comment by fingolfin** [comment]
OK, so how is the process for fink development these days? Is anybody doing PR review and merging? Or am I supposed to just do it myself? (I would kind of prefer the former, i.e. get some additional eyes looking at any changes I contribute, but if nobody is willing to do it, I can of course also do the other for my three open PRs, and future PRs)

**Comment by TheSin-** [comment]
well I'm still waiting year and year later with no input... so....

**Comment by akhansen** [comment]
Ideally, yeah, we'd like to have at least one other person from Core look at a PR and test it.  I'm all in favor of a robust change management process.

In practice, given limited personnel resources, a more typical case is that someone who understands the scope and ramifications of the changes eventually signs off without actually injecting the update, and possibly only after the submitter reminds everybody that the PR exists.

**Comment by dmacks** [comment]
I merged it. But I agree that for small stuff "works for me" and "sure, go ahead and do whatever you're doing" are probably okay. Especially while we're all learning git and github.

**Pull request merged**
