### PR TITLE
Check for qmake .prl files containing builddir (Issues #157)

### PR DESCRIPTION
**Pull request by dmacks**

### CODE REVIEW

**Comment by akhansen** [comment]
Issue #157

**Comment by akhansen** [comment]
Looks reasonable to me.  
While we're at it, maybe get rid of the postinst .la cleaner at the same time?

**Comment by dmacks** [comment]
PostInst .la cleaner would require that we had an InstallScript to clear that data. IIRC, .la otherwise are still containing a ton of flags that trigger IBD.

**Comment by TheSin-** [comment]
I agree .la cleaning should be done during or after the fink build-install phase before the deb is created, feel free to take my version of this form my PR since it already moves it to where it should be.

The problem with it, is all currently built debs are no good once this is done since they will container invalid .la files.  So maybe we need fink to warn about it if it's installing a deb with bad .la ?  This change should be made to longer we go the harder it'll be like everything else.

**Pull request merged**
